'use client';

import { useEffect, useState } from 'react';

const domains = [
  ['01', 'Kesiapsiagaan & respons', 'Laporan warga, peta risiko, kontak darurat, dan pusat operasi.'], ['02', 'Kesehatan warga', 'Posyandu, Posbindu, donor darah, gizi, dan pendampingan.'], ['03', 'Lingkungan & sanitasi', 'Sampah, drainase, genangan, penghijauan, dan perubahan iklim.'], ['04', 'Perlindungan sosial', 'Warga rentan, permintaan bantuan, relawan, dan persetujuan akses.'], ['05', 'Air, pangan & gizi', 'Sumber air, dapur umum, stok bencana, urban farming, dan gizi.'], ['06', 'Ekonomi & UMKM', 'Pendataan usaha, penguatan kapasitas, kolaborasi, dan akses pasar.'], ['07', 'Pendidikan & pemuda', 'Edukasi kebencanaan, simulasi, relawan muda, kuis, dan sertifikat.'], ['08', 'Seni, budaya & komunitas', 'Agenda kampung, ruang karya, tradisi lokal, dan partisipasi lintas usia.'],
];
const flow = [['01','●','Laporkan','Kirim kondisi, kebutuhan, atau gagasan dari ponsel.'],['02','◆','Koordinasikan','Pengurus memverifikasi, memetakan, dan membagi tugas.'],['03','✓','Tindak lanjuti','Progres dicatat, warga mendapat kabar, hasil dapat dievaluasi.']];
const trust = [['AKSES','Sesuai peran','Data sensitif hanya tampil untuk pengguna yang berwenang.'],['PRIVASI','Persetujuan jelas','Data warga rentan dan kesehatan diproses dengan pembatasan akses.'],['DARURAT','Bukan layanan darurat','Untuk keadaan darurat tetap hubungi 112 / 119 dan layanan resmi.']];

export default function Home() {
  const [dark,setDark]=useState(false); const [menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
  return <main className="site-shell">
    <header className="navigation"><a className="brand" href="#beranda"><img className="brand-emblem" src="/assets/kundalini-emblem.png" alt=""/><img className="brand-wordmark" src="/assets/kundalini-wordmark.png" alt="KUNDALINI"/></a><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Buka menu">{menuOpen?'×':'☰'}</button><nav className={menuOpen?'nav-links is-open':'nav-links'}><a href="#ekosistem">Ekosistem</a><a href="#fitur">Fitur</a><a href="#cara-kerja">Cara kerja</a><a href="#keamanan">Keamanan</a><button className="theme-button" onClick={()=>setDark(!dark)} aria-label="Ganti tampilan terang atau gelap">{dark?'☀':'◐'}</button><a className="button button-primary" href="https://app.kundalini.sbs">Buka aplikasi</a></nav></header>
    <section className="hero section-pad" id="beranda"><div className="hero-copy"><span className="eyebrow">PUSAT KOLABORASI KAMPUNG KUNCEN</span><h1>Kampung terhubung.<br/>Warga lebih siap.</h1><p className="javanese">ꦏꦸꦤ꧀ꦢꦭꦶꦤꦶ</p><p className="lead">Satu ruang digital untuk laporan warga, koordinasi pengurus, kesiapsiagaan, kesehatan, lingkungan, dan penguatan ekonomi kampung.</p><div className="button-row"><a className="button button-primary" href="https://app.kundalini.sbs">Buka aplikasi</a><a className="button button-secondary" href="#ekosistem">Pelajari ekosistem</a></div><p className="caption">Resmi di <b>app.kundalini.sbs</b> · Informasi publik di <b>www.kundalini.sbs</b></p></div><div className="app-window"><i className="atlas orbit-one"/><i className="atlas orbit-two"/><article className="phone phone-light"><img src="/assets/app-light.png" alt="Tampilan aplikasi KUNDALINI mode terang"/></article><article className="phone phone-dark"><img src="/assets/app-dark.png" alt="Tampilan aplikasi KUNDALINI mode gelap"/></article><span className="mode-label">ADAPTIF · TERANG + GELAP</span></div></section>
    <section className="ecosystem-strip">{['Warga','Pengurus Kampung','Jaga Warga','KTB Kuncen'].map((item,index)=><div className="ecosystem-item" key={item}><span>0{index+1}</span><strong>{item}</strong></div>)}</section>
    <section className="domains section-pad" id="ekosistem"><div className="section-heading split-heading"><h2>Satu ekosistem,<br/>delapan lini kehidupan.</h2><p>Setiap modul berdiri mandiri, tetapi terhubung melalui laporan, peta, koordinasi, dan tindak lanjut yang dapat dipantau.</p></div><div className="domain-grid" id="fitur">{domains.map(([n,t,d])=><article className="domain-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="flow-section section-pad" id="cara-kerja"><div className="section-heading split-heading inverted"><h2>Dari kabar warga<br/>menjadi aksi bersama.</h2><p>Alur dibuat ringkas agar mudah digunakan oleh warga dengan beragam tingkat pengalaman digital.</p></div><div className="flow-grid">{flow.map(([n,i,t,d])=><article className="flow-card" key={n}><span>{n}</span><b>{i}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="trust-section section-pad" id="keamanan"><div className="section-heading"><h2>Teknologi yang menjaga manusia<br/>tetap memegang kendali.</h2></div><div className="trust-grid">{trust.map(([l,t,d])=><article className="trust-card" key={l}><span>{l}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="final-cta section-pad"><div><p className="javanese">ꦏꦸꦤ꧀ꦢꦭꦶꦤꦶ</p><h2>Kuncen Digdaya<br/>di Segala Lini.</h2><p>Mulai dari laporan kecil, tumbuhkan kolaborasi yang berdampak untuk semua generasi.</p><a className="button button-primary" href="https://app.kundalini.sbs">Buka aplikasi</a></div><img src="/assets/kundalini-emblem.png" alt="Emblem KUNDALINI"/></section>
    <footer className="footer"><div className="footer-brand"><img src="/assets/kundalini-wordmark-white.svg" alt="KUNDALINI"/><p>Pusat Kolaborasi dan Ketangguhan Kampung Kuncen</p></div><div><a href="https://app.kundalini.sbs">app.kundalini.sbs</a><a href="#beranda">www.kundalini.sbs</a><small>© 2026 KUNDALINI</small></div></footer>
  </main>;
}
